name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-podman:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: [ 'alpine', 'debian' ]
        engine: [ 'podman', 'docker' ]
    steps:
      - run: ln -s /etc/passwd /tmp/beans
      - name: Pull
        run: ${{ matrix.engine }} pull ${{ matrix.image }}
      - run: ${{ matrix.engine }} run ${{ matrix.image }} ls /tmp
      - run: ${{ matrix.engine }} run -v /tmp/beans:/wow:ro ${{ matrix.image }} ls /tmp
