name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-engine:
    name: Test across container engines
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/checkout@v2
      - name: Install
        run: |
          podman pull fnndsc/pl-simpledsapp:2.0.0
          mkdir in out
          touch in/a

      - name: wo script
        run: |
          python << EOF
          from subprocess import run
          from os import environ
          e = {}
          e.update(environ)
          cmd = 'exec podman run --rm -v /etc/localtime:/etc/localtime:ro -v /home/runner/work/chrispile/chrispile/in:/incoming:ro -v /home/runner/work/chrispile/chrispile/out:/outgoing:rw fnndsc/pl-simpledsapp:2.0.0 ls /incoming'
          run(['bash', '-xs', '-'], input=cmd, env=e, text=True, check=True)
      
      # - name: Real run
      #   env:
      #     ENGINE_TO_TEST: ${{ matrix.container-engine }}
      #   run: test/with_engine_mask.sh chrispile run fnndsc/pl-simpledsapp:2.0.0 in out