name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-engine:
    name: Test across container engines
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/checkout@v2
      - name: Install
        run: |
          podman pull python:3.9.1-slim-buster
          mkdir in out
          touch in/a

      - name: wo script
        run: podman run --rm -v /etc/localtime:/etc/localtime:ro -v /home/runner/work/chrispile/chrispile/in:/incoming:ro python:3.9.1-slim-buster ls /incoming
      
      # - name: Real run
      #   env:
      #     ENGINE_TO_TEST: ${{ matrix.container-engine }}
      #   run: test/with_engine_mask.sh chrispile run fnndsc/pl-simpledsapp:2.0.0 in out