name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-engine:
    name: Test across container engines
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/checkout@v2
      - name: Install
        run: |
          podman pull python:3.9.1-slim-buster
          mkdir /tmp/folder
          touch /tmp/folder/bean

      - name: Test
        run: podman run --rm -v /etc/localtime:/etc/localtime:ro -v /tmp/folder:/wack:ro python:3.9.1-slim-buster ls /wack
      