name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-podman:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: [ 'alpine', 'python:3.9.1-slim-buster' ]
        engine: [ 'podman', 'docker' ]
    steps:
      # - uses: actions/checkout@v2
      - name: Install
        run: |
          ${{ matrix.engine }} pull ${{ matrix.image }}
          mkdir /tmp/folder
          touch /tmp/folder/bean
      - run: ${{ matrix.engine }} run ${{ matrix.image }} ls /tmp
      - run: ${{ matrix.engine }} run -v /etc/localtime:/etc/localtime:ro ${{ matrix.image }} ls /tmp
      - run: ${{ matrix.engine }} run -v /tmp/folder:/wack:ro ${{ matrix.image }} ls /tmp
      - run: ${{ matrix.engine }} run -v /etc/localtime:/etc/localtime:ro -v /tmp/folder:/wack:ro ${{ matrix.image }} ls /tmp
