name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-podman:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: [ 'alpine', 'debian' ]
        engine: [ 'podman', 'docker' ]
    steps:
      - name: Pull
        run: ${{ matrix.engine }} pull ${{ matrix.image }}
      - run: stat /etc/localtime
      - run: ${{ matrix.engine }} run ${{ matrix.image }} ls /tmp
      - run: ${{ matrix.engine }} run -v /etc/localtime:/etc/localtime:ro ${{ matrix.image }} ls /tmp
